### PR TITLE
Allow for external log banners.

### PR DESCRIPTION
**Pull request by rabbah**
## Description

Factors the activation banner printing into a function that can be overriden.

## Related Issue

See https://github.com/adobe/aio-lib-runtime/issues/27.

## Motivation and Context

This refactoring is semantic preserving but provides flexibility for downstream plugins to provide their own banner implementation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by rabbah** [comment]
There are two commits in the PR. The first is an unrefined implementation and the second allows for a clean external override. Of course, I am open to other and better suggestions.

**Comment by rabbah** [comment]
Conflict resolved.

**Comment by Himavanth** [comment]
@rabbah What do you think about reusing the `logger` argument on `printFilteredActionLogs` to make this feature more "accessible" ? 
Say to use a custom banner, user can call `printFilteredActionLogs (runtime, {bannerFunc: myCustomBannerFunc}, 1)`.
For custom banner and logger, it would be`printFilteredActionLogs (runtime, {logFunc: myLogger, bannerFunc: myCustomBannerFunc}, 1)`.

And for backward compatibility, to just use a custom logger, the call can also be `printFilteredActionLogs (runtime, myLogger, 1)`.

@purplecabbage WDYT

**Comment by rabbah** [comment]
Thanks for the suggestion. I’ll defer to your judgement and @purplecabbage. 

With your suggestion, the banner printing function would need to be threaded to printActivationLogs from the parent call sites, correct?

**Comment by rabbah** [comment]
@Himavanth I think the approach you're suggesting is similar to the first patch I proposed here https://github.com/adobe/aio-lib-runtime/issues/27#issue-793927503. I'm happy to make this change when you confirm the preferred approach.

**Comment by Himavanth** [comment]
@rabbah Indeed. My suggestion does seem very similar to the approach you mentioned in that issue. 
Only exception would be the second case (i talked about above) where both logFunc and bannerFunc are custom. 
I'm not clear how this case would work with your code but my suggestion was  `printFilteredActionLogs (runtime, {logFunc: myLogger, bannerFunc: myCustomBannerFunc}, 1)`. 
Let's go ahead with your first patch and also cover the above case (maybe it's already covered).

**Comment by rabbah** [comment]
@Himavanth revised according to discussion.

**Comment by Himavanth** [comment]
Thx for the changes @rabbah .

**Pull request merged**
