### PR TITLE
Memory limits follow documentation

### PR DESCRIPTION
**Pull request by fe-lix-**
## Description

Adobe Documentation state that memory limits should be configured as follow in the `app.config.yaml`

```
application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      mypackage:
        actions:
          myactions:
            function: actions/myaction.js
            runtime: 'nodejs:14'
            limits:
              memory: 512
```

Currently the code only looks for property `memorySize` and not `memory`

[Documentation 1](https://developer.adobe.com/app-builder/docs/guides/appbuilder-configuration/#runtime-manifest)

[Documentation 2](https://developer.adobe.com/runtime/docs/guides/using/system_settings/)

## Related Issue

#105 

## Motivation and Context

The behaviour difference has been found by a customer here : https://experienceleaguecommunities.adobe.com/t5/project-firefly-questions/can-t-change-action-memory-limit/td-p/454197

## How Has This Been Tested?

- Automated tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by moritzraho — APPROVED** [review]

**Review by arjuncooliitr — APPROVED** [review]
LGTM

**Comment by purplecabbage** [comment]
It looks like the docs were wrong, OpenWhisk defines `memorySize` as the value ...
https://github.com/apache/openwhisk-wskdeploy/blob/03df1126c3b5205d642738479a08bb7cd66a03b3/tests/dat/manifest_data_compose_actions_for_limits.yaml#L29

Should we change this to support both?

**Comment by arjuncooliitr** [comment]
Yes I think we should change our docs and support both `memory` and `memorySize` inputs

**Comment by fe-lix-** [comment]
I think `wskdeploy` and the OpenWhisk API do not agree that probably what stems the confusion.

`wskdeploy` use `memorySize` but the OpenWhisk API uses `memory`.

https://github.com/apache/openwhisk/blob/59b67fe96f44e573f3348afed966a1cdaf80ddf2/docs/reference.md?plain=1#L80

**Comment by purplecabbage** [comment]
Merging, thanks @fe-lix- 
I missed that you are in fact supporting both!

**Pull request merged**
