### PR TITLE
breaking change: new validators

### PR DESCRIPTION
**Pull request by moritzraho**
## Description
required for https://github.com/adobe/aio-cli-plugin-app/pull/417/
`Major version bump` because the validators have changed

## Before merge, revert these changes

- [x] re-add `npm test` (git revert bf949f2)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
On Windows, `build.action.test` is taking a long time and fails:
```
 RUNS  test/build.actions.test.js

<--- Last few GCs --->
= [32776:0000027D12E29E20]    40720 ms: Mark-sweep (reduce) 4095.4 (4101.1) -> 4094.7 (4102.4) MB, 2419.1 / 0.0 ms  (+ 0.0 ms in 17 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2422 ms) (average mu = 0.105, current mu =[32776:0000027D12E29E20]    45178 ms: Mark-sweep (reduce) 4095.9 (4101.4) -> 4095.1 (4102.6) MB, 4456.3 / 0.0 ms  (+ 0.0 ms in 17 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 4458 ms) (average mu = 0.039, current mu =

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF792E63E0F napi_wrap+108911
 2: 00007FF792E07E16 v8::base::CPU::has_sse+61910
 3: 00007FF792E08D16 node::OnFatalError+294
 4: 00007FF7936E0CEE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7936C5ACD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF79356F95C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1516
 7: 00007FF79357ACEA v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF793577E99 v8::internal::Heap::PageFlagsAreConsistent+2457
 9: 00007FF79356CA71 v8::internal::Heap::CollectGarbage+2033
10: 00007FF79356AC95 v8::internal::Heap::AllocateExternalBackingStore+1349
11: 00007FF79358AFEB v8::internal::Factory::NewFillerObject+203
12: 00007FF7932B9E0F v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1039
13: 00007FF793769BAD v8::internal::SetupIsolateDelegate::SetupHeap+465229
14: 000003E35FD913FF
```
This does not occur on Linux.

**Comment by shazron** [comment]
Focusing on fixing the tests on Linux,  re-enable `npm test` and letting the GH CI test on Windows after (maybe it's my system).

**Comment by moritzraho** [comment]
hmm is the using too much memory ? but yes +1 to first focus on linux

**Comment by shazron** [comment]
closing the loop: Windows tests had an infinite loop because determining the root path was incorrect: fixed in 0073ed3

**Comment by shazron** [comment]
all unit tests pass on Windows and Linux, with 100% code coverage 👍

**Pull request merged**
