### PR TITLE
Support stage env for validators

### PR DESCRIPTION
**Pull request by moritzraho**
## Description
using adobe/aio-lib-env

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
tested `AIO_CLI_ENV=stage|prod` with runtime plugin deploy manifest and app plugin deploy. Verified using debug logs

**Comment by moritzraho** [comment]
cc @Himavanth @meryllblanchet @purplecabbage @rajarju @sandeep-paliwal  @sarahxxu @shazron

**Review by shazron — APPROVED** [review]

**Review by purplecabbage — COMMENTED** [review]
The changes are good looked at in isolation, however we need a more holistic look at this to prevent redoing things.
I think it makes more sense to have the `stage|prod` determined before even getting to this code, and having it passed in as part of either appConfig or deployConfig.  This does not _only_ affect the shared-validators, but every action that is deployed needs to know if it is `stage|prod` so when the aio-sdk is loaded inside the action, it knows which TVM to call inside the aio-lib-files for example.

That said, does it also make more sense to not have the headless+headless-stage validators separated, but instead passed a param to indicate whether it should validate the stage|prod way?  I see this as a question of just how deeply we want to split stage&prod.

**Comment by moritzraho** [comment]
> The changes are good looked at in isolation, however we need a more holistic look at this to prevent redoing things.
I think it makes more sense to have the stage|prod determined before even getting to this code, and having it passed in as part of either appConfig or deployConfig.

Yes I understand your point. But let's discuss this further, here is the execution flow for deploying validators for both the runtime and app plugin:

`app deploy` => `commands/app/deploy` => `aio-lib-runtime/index` => `aio-lib-runtime/deploy-actions` => `aio-lib-runtime/utils.processPackage` => `aio-lib-runtime/utils.rewriteActionsWithAdobeAuthAnnotation`

`rt deploy` => `commands/runtime/deploy/index` => `aio-lib-runtime/index` => `aio-lib-runtime/utils.processPackage` => `aio-lib-runtime/utils.rewriteActionsWithAdobeAuthAnnotation`

`rt sync` => `commands/runtime/deploy/sync` => `aio-lib-runtime/index` => `aio-lib-runtime/utils.processPackage` => `aio-lib-runtime/utils.rewriteActionsWithAdobeAuthAnnotation`


As you can see this would mean propagating an `env` argument through all those methods and modules. Also every other caller of `utils.processPackage` will have to eventually also manage and pass the `env` parameter. Worst future methods/commands calling `processPackage` would need to re-implement `env` management.
I think that's why @shazron designed the `aio-lib-env` module to make it possible to read the environment from every module independently from the call stack.
Also let's not forget that Runtime is moving to IMS and a lot of IMS related work will be done in the runtime-lib/app-plugin/runtime-plugin, which will give us a chance to refactor if needed 🙂 

>  This does not only affect the shared-validators, but every action that is deployed needs to know if it is stage|prod so when the aio-sdk is loaded inside the action, it knows which TVM to call inside the aio-lib-files for example.

Yes good point and I agree apart from one subtly: 
IMO the env loading and parsing should be done in `aio-lib-core-tvm` instead of `aio-sdk`. The reason being that users might interact with files or state directly without using `aio-sdk`. `aio-lib-core-tvm` is the "lowest" common library interacting with the TVM just like `aio-lib-runtime` in the case of the validators 😉. Libraries should be usable independently.

> That said, does it also make more sense to not have the headless+headless-stage validators separated, but instead passed a param to indicate whether it should validate the stage|prod way? I see this as a question of just how deeply we want to split stage&prod.

Yes. We can do that when moving to the unique xt-reg validator 🙂

**Comment by purplecabbage** [comment]
By _`... aio-sdk is loaded inside the action ... `_ I meant aio-sdk and every library in it
aio-lib-file should know to call a stage-url when loaded by a 'ims-stage' env action.

I think for the sake of sanity that this would apply to aio-lib-files, aio-lib-state, and aio-core-lib-tvm but NOT target/campaign-standard/analytics ...

**Comment by purplecabbage** [comment]
> re: execution flow for deploying

The config is passed around to all these functions, I am not suggesting adding another argument, just another value in the loaded appConfig that is passed from app-plugin => runtime-lib

**Comment by moritzraho** [comment]
> re: execution flow for deploying
> The config is passed around to all these functions, I am not suggesting adding another argument, just another value in the loaded appConfig that is passed from app-plugin => runtime-lib

Config is passed to `aio-lib-runtime/deploy-actions` when calling via plugin app, but it's not passed to any of the utils functions.. So most of the functions in the call stack would need the env arg. but there is probably a way to improve this

**Pull request merged**
